# 应用服务 WEB 访问端口
server:
  port: 8080

# 应用名称
spring:
  application:
    name: finace-data-extract
  datasource:
    maxActive: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.126.206:33306/finace_data?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&&serverTimezone=GMT%2b8
    username: root
    password: Lysss_0203
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
  flyway:
    clean-disabled: true
    enabled: true
    out-of-order: false
    baseline-on-migrate: true
    baseline-version: 0
  mail:
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      "[mail.smtp.socketFactory.port]": 465
      "[mail.smtp.socketFactory.fallback]": false
      "[mail.smtp.socketFactory.class]": javax.net.ssl.SSLSocketFactory
    host: smtp.qq.com
    username: liuyang.sx@qq.com
    password: ubirhgowotnnbedd
    sender: liuyang.sx@qq.com
    receiver: 1042133944@qq.com,18335124922@139.com
#  thymeleaf:
#    prefix: classpath:/templates/
#    mode: HTML
#    cache: false
#    encoding: UTF-8
#    servlet:
#      content-type: text/html

resources:
  fund:
    uri:  "https://push2.eastmoney.com/api/qt/ulist.np/get"
    fields:  "fields=f1,f2,f3,f4,f5,f6,f10,f11,f12,f13,f14,f15,f16,f17,f18"
    url: ${resources.fund.uri}"?"${resources.fund.fields}"&secids={secids}&ut=6d2ffaa6a585d612eda28417681d58fb&_={tm}"
  metal:
    url: https://mybank.icbc.com.cn/servlet/AsynGetDataServlet



schedule:
  metal:
    cron: "0 0/30 0 ? * 1/6"
  fund:
    cron: "0 0/10 9-15 * * ?"
  analyse:
    cron:
      daily: "0 30 15 * * ?"
      week: "0 0 17 ? * 5 *"
      month: "0 0 17 L * ?"
  notify:
    cron: "0 40 14 * * ?"
